### ISSUE TITLE
코드리뷰 부탁드립니다.

### ISSUE THREAD

**Issue by Shinheeje** [Shinheeje/react_week2_test#1]
1. state에 저장되는 값이 객체여서 이 값을 redux에 어떻게 보내야 되는지 고민을 많이 했다.

2. styled-components 를 사용했는데 변수명을 어떻게 설정해야될지 고민 된다.

**Comment by WooMinGy** [comment]
희제님 다음부터는 꼭! 질문 형식으로 부탁드려요ㅎㅎ
아까 설명 드렸다시피 코드짜는 스타일(ex. camelCase 등)을 알아보면 좋을 것 같고, 불필요한 코드(ex. console.log()) 삭제하는 습관 가지시면 좋습니다!
로직적인 부분에서는 깔끔하게 잘 짜셔서 이대로 쭉 공부하시면 잘 하실 것 같네요!
